# Generated by Django 6.0.6 on 2026-06-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_updated_at_alter_post_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('level', models.IntegerField(choices=[(1, '1단계 (최고위험)'), (2, '2단계 (주요경보)'), (3, '3단계 (일반주의)')])),
                ('confidence', models.FloatField()),
                ('message', models.TextField()),
                ('video_file', models.CharField(blank=True, max_length=255, null=True)),
                ('is_permanent', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SystemExceptionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('level', models.IntegerField()),
                ('file_name', models.CharField(max_length=100)),
                ('line_number', models.IntegerField()),
                ('message', models.TextField()),
                ('code_snippet', models.TextField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
        ),
    ]
